// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "typography": {
      name: "typography",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/magicui/typography.tsx"],
      component: React.lazy(() => import("@/registry/default/magicui/typography.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "textbox": {
      name: "textbox",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/magicui/textbox.tsx"],
      component: React.lazy(() => import("@/registry/default/magicui/textbox.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "animate": {
      name: "animate",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/magicui/animate.tsx"],
      component: React.lazy(() => import("@/registry/default/magicui/animate.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "background": {
      name: "background",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/magicui/background.tsx"],
      component: React.lazy(() => import("@/registry/default/magicui/background.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-demo": {
      name: "typography-demo",
      type: "registry:example",
      registryDependencies: ["typography"],
      files: ["registry/default//example/typography-demo.tsx"],
      component: React.lazy(() => import("@/registry/default//example/typography-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "textbox-demo": {
      name: "textbox-demo",
      type: "registry:example",
      registryDependencies: ["textbox"],
      files: ["registry/default//example/textbox-demo.tsx"],
      component: React.lazy(() => import("@/registry/default//example/textbox-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "animate-demo": {
      name: "animate-demo",
      type: "registry:example",
      registryDependencies: ["animate"],
      files: ["registry/default//example/animate-demo.tsx"],
      component: React.lazy(() => import("@/registry/default//example/animate-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "background-demo": {
      name: "background-demo",
      type: "registry:example",
      registryDependencies: ["background"],
      files: ["registry/default//example/background-demo.tsx"],
      component: React.lazy(() => import("@/registry/default//example/background-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
